name: Build

on: [push]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Ensure we can build the Score Server
      run: docker build -t test:test --target server .
    - name: Ensure we can build the Score Client
      run: docker build -t test:test --target client .